CREATE TABLE PATIENTS (
    Id UUID NOT NULL PRIMARY KEY,
    BIRTHDATE DATE NOT NULL CHECK (BIRTHDATE <= CURRENT_DATE),
    DEATHDATE DATE CHECK (DEATHDATE <= CURRENT_DATE),
    SSN VARCHAR(11) NOT NULL,
    DRIVERS VARCHAR(9),
    PASSPORT VARCHAR(10),
    PREFIX VARCHAR(4),
    FIRST VARCHAR(30) NOT NULL,
    LAST VARCHAR(30) NOT NULL,
    SUFFIX VARCHAR(5),
    MAIDEN VARCHAR(30),
    MARTIAL CHAR(1),
    RACE VARCHAR(10) NOT NULL ,
    ETHNICITY VARCHAR(20) NOT NULL ,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    BIRTHPLACE VARCHAR(50),
    ADDRESS VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(30),
    COUNTY VARCHAR(30),
    ZIP VARCHAR(5),
    LAT DECIMAL(11,8),
    LON DECIMAL(11,8),
    HEALTHCARE_EXPENSES DECIMAL(15,4),
    HEALTHCARE_COVERAGE DECIMAL(15,4)
);

CREATE TABLE PAYERS (
    Id UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE_HEADQUARTERED VARCHAR(5) NOT NULL,
    ZIP VARCHAR(5),
    PHONE VARCHAR(14),
    AMOUNT_COVERED NUMERIC(15,2) NOT NULL,
    AMOUNT_UNCOVERED NUMERIC(15,2) NOT NULL,
    REVENUE NUMERIC(15,2) NOT NULL,
    COVERED_ENCOUNTERS INT NOT NULL,
    UNCOVERED_ENCOUNTERS INT NOT NULL,
    COVERED_MEDICATIONS INT NOT NULL,
    UNCOVERED_MEDICATIONS INT NOT NULL,
    COVERED_PROCEDURES INT NOT NULL,
    UNCOVERED_PROCEDURES INT NOT NULL,
    COVERED_IMMUNIZATIONS INT NOT NULL,
    UNCOVERED_IMMUNIZATIONS INT NOT NULL,
    UNIQUE_CUSTOMERS INT NOT NULL,
    QOLS_AVG NUMERIC(15,14) NOT NULL,
    MEMBER_MONTHS INT NOT NULL
);

CREATE TABLE PAYER_TRANSITIONS (
    PATIENT UUID NOT NULL,
    MEMBERID UUID NOT NULL,
    START_YEAR TIMESTAMPTZ NOT NULL,
    END_YEAR TIMESTAMPTZ NOT NULL,
    PAYER UUID NOT NULL,
    SECONDARY_PAYER UUID,
    OWNERSHIP VARCHAR(10) NOT NULL,
    OWNERNAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (PATIENT, MEMBERID, START_YEAR)
);

CREATE TABLE PROCEDURES (
    START TIMESTAMPTZ NOT NULL,
    STOP TIMESTAMPTZ NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_COST NUMERIC(10,2) NOT NULL,
    REASONCODE VARCHAR(10),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE PROVIDERS (
    Id UUID NOT NULL PRIMARY KEY,
    ORGANIZATION UUID NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    SPECIALITY VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(5) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    LAT DECIMAL(11, 8) NOT NULL,
    LON DECIMAL(11, 8) NOT NULL,
    UTILIZATION INT NOT NULL
);

CREATE TABLE SUPPLIES (
    DATE DATE NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(12) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (DATE, PATIENT, ENCOUNTER, CODE)
);

CREATE TABLE ENCOUNTERS (
    Id UUID PRIMARY KEY,
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ORGANIZATION UUID NOT NULL,
    PROVIDER UUID NOT NULL,
    PAYER UUID NOT NULL,
    ENCOUNTERCLASS VARCHAR(50) NOT NULL,
    CODE VARCHAR(12) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_ENCOUNTER_COST DECIMAL(10, 2) NOT NULL,
    TOTAL_CLAIM_COST DECIMAL(10, 2) NOT NULL,
    PAYER_COVERAGE DECIMAL(10, 2) NOT NULL,
    REASONCODE VARCHAR(12),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE IMAGING_STUDIES (
    Id UUID PRIMARY KEY,
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    SERIES_UID VARCHAR(255) NOT NULL,
    BODYSITE_CODE VARCHAR(12) NOT NULL,
    BODYSITE_DESCRIPTION VARCHAR(255) NOT NULL,
    MODALITY_CODE VARCHAR(5) NOT NULL,
    MODALITY_DESCRIPTION VARCHAR(255) NOT NULL,
    INSTANCE_UID VARCHAR(255) NOT NULL,
    SOP_CODE VARCHAR(255) NOT NULL,
    SOP_DESCRIPTION VARCHAR(255) NOT NULL,
    PROCEDURE_CODE VARCHAR(20) NOT NULL
);

CREATE TABLE IMMUNIZATIONS (
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(5) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_COST DECIMAL(10, 2) NOT NULL
);

CREATE TABLE MEDICATIONS (
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    PAYER UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(12) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_COST DECIMAL(10, 2) NOT NULL,
    PAYER_COVERAGE DECIMAL(10, 2),
    DISPENSES INT NOT NULL,
    TOTALCOST DECIMAL(10, 2) NOT NULL,
    REASONCODE VARCHAR(255),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE OBSERVATIONS (
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL,
    CODE VARCHAR(12) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    VALUE VARCHAR(100) NOT NULL,
    UNITS VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL
);

CREATE TABLE ORGANIZATIONS (
    Id UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP VARCHAR(5) NOT NULL,
    LAT DECIMAL(11, 8) NOT NULL,
    LON DECIMAL(11, 8) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    REVENUE DECIMAL(10, 2) NOT NULL,
    UTILIZATION INT NOT NULL
);

