CREATE TEMP TABLE IMAGING_STUDIES_STAGING (
    Id TEXT,
    DATE TEXT,
    PATIENT TEXT,
    ENCOUNTER TEXT,
    SERIES_UID TEXT,
    BODYSITE_CODE TEXT,
    BODYSITE_DESCRIPTION TEXT,
    MODALITY_CODE TEXT,
    MODALITY_DESCRIPTION TEXT,
    INSTANCE_UID TEXT,
    SOP_CODE TEXT,
    SOP_DESCRIPTION TEXT,
    PROCEDURE_CODE TEXT
);

COPY IMAGING_STUDIES_STAGING FROM '/tmp/imaging_studies.csv' DELIMITER ',' CSV HEADER;

INSERT INTO IMAGING_STUDIES (
    Id,
    DATE,
    PATIENT,
    ENCOUNTER,
    SERIES_UID,
    BODYSITE_CODE,
    BODYSITE_DESCRIPTION,
    MODALITY_CODE,
    MODALITY_DESCRIPTION,
    INSTANCE_UID,
    SOP_CODE,
    SOP_DESCRIPTION,
    PROCEDURE_CODE
)
SELECT
    Id::UUID,
        DATE::TIMESTAMP,
    PATIENT::UUID,
        ENCOUNTER::UUID,
        SERIES_UID,
    BODYSITE_CODE,
    BODYSITE_DESCRIPTION,
    MODALITY_CODE,
    MODALITY_DESCRIPTION,
    INSTANCE_UID,
    SOP_CODE,
    SOP_DESCRIPTION,
    PROCEDURE_CODE
FROM IMAGING_STUDIES_STAGING
    ON CONFLICT (Id) DO NOTHING;

DROP TABLE IMAGING_STUDIES_STAGING;