DROP TABLE IF EXISTS CLAIMS_TRANSACTIONS;
DROP TABLE IF EXISTS CLAIMS;
DROP TABLE IF EXISTS ALLERGIES;
DROP TABLE IF EXISTS CAREPLANS;
DROP TABLE IF EXISTS CONDITIONS;
DROP TABLE IF EXISTS DEVICES;
DROP TABLE IF EXISTS IMMUNIZATIONS;
DROP TABLE IF EXISTS IMAGING_STUDIES;
DROP TABLE IF EXISTS MEDICATIONS;
DROP TABLE IF EXISTS OBSERVATIONS;
DROP TABLE IF EXISTS PROCEDURES;
DROP TABLE IF EXISTS SUPPLIES;
DROP TABLE IF EXISTS ENCOUNTERS;
DROP TABLE IF EXISTS PROVIDERS;
DROP TABLE IF EXISTS PAYER_TRANSITIONS;
DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS PAYERS;
DROP TABLE IF EXISTS ORGANIZATIONS;

--TABLES----------------------------------------------------------------------------------------------------------------
CREATE TABLE PATIENTS (
    Id UUID NOT NULL PRIMARY KEY,
    BIRTHDATE DATE NOT NULL CHECK (BIRTHDATE <= CURRENT_DATE),
    DEATHDATE DATE CHECK (DEATHDATE <= CURRENT_DATE),
    SSN VARCHAR(11) NOT NULL,
    DRIVERS VARCHAR(9),
    PASSPORT VARCHAR(10),
    PREFIX VARCHAR(4),
    FIRST VARCHAR(30) NOT NULL,
    LAST VARCHAR(30) NOT NULL,
    SUFFIX VARCHAR(5),
    MAIDEN VARCHAR(30),
    MARTIAL CHAR(1),
    RACE VARCHAR(10) NOT NULL ,
    ETHNICITY VARCHAR(20) NOT NULL ,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    BIRTHPLACE VARCHAR(100),
    ADDRESS VARCHAR(100),
    CITY VARCHAR(50),
    STATE VARCHAR(30),
    COUNTY VARCHAR(30),
    ZIP VARCHAR(15),
    LAT DECIMAL(11,8),
    LON DECIMAL(11,8),
    HEALTHCARE_EXPENSES DECIMAL(15,4),
    HEALTHCARE_COVERAGE DECIMAL(15,4)
);

CREATE TABLE PAYERS (
    Id UUID NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(100),
    CITY VARCHAR(50),
    STATE_HEADQUARTERED VARCHAR(5),
    ZIP VARCHAR(15),
    PHONE VARCHAR(14),
    AMOUNT_COVERED NUMERIC(15,2),
    AMOUNT_UNCOVERED NUMERIC(15,2),
    REVENUE NUMERIC(15,2),
    COVERED_ENCOUNTERS INT,
    UNCOVERED_ENCOUNTERS INT,
    COVERED_MEDICATIONS INT,
    UNCOVERED_MEDICATIONS INT,
    COVERED_PROCEDURES INT,
    UNCOVERED_PROCEDURES INT,
    COVERED_IMMUNIZATIONS INT,
    UNCOVERED_IMMUNIZATIONS INT,
    UNIQUE_CUSTOMERS INT,
    QOLS_AVG NUMERIC(15,14),
    MEMBER_MONTHS INT
);

ALTER TABLE PATIENTS ADD CONSTRAINT unique_ssn UNIQUE (SSN);

CREATE TABLE PAYER_TRANSITIONS (
    PATIENT UUID NOT NULL,
    MEMBERID UUID,
    START_YEAR TIMESTAMPTZ,
    END_YEAR TIMESTAMPTZ,
    PAYER UUID NOT NULL,
    SECONDARY_PAYER UUID,
    OWNERSHIP VARCHAR(10),
    OWNERNAME VARCHAR(100)
);

CREATE TABLE PROCEDURES (
    START TIMESTAMPTZ NOT NULL,
    STOP TIMESTAMPTZ NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_COST NUMERIC(10,2) NOT NULL,
    REASONCODE VARCHAR(10),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE PROVIDERS (
    Id UUID NOT NULL PRIMARY KEY,
    ORGANIZATION UUID NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M', 'F')),
    SPECIALITY VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(20) NOT NULL,
    ZIP VARCHAR(15) NOT NULL,
    LAT DECIMAL(11, 8) NOT NULL,
    LON DECIMAL(11, 8) NOT NULL,
    UTILIZATION INT NOT NULL
);

CREATE TABLE SUPPLIES (
    DATE DATE NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    QUANTITY INT NOT NULL
);

CREATE TABLE ENCOUNTERS (
    Id UUID PRIMARY KEY,
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ORGANIZATION UUID NOT NULL,
    PROVIDER UUID NOT NULL,
    PAYER UUID NOT NULL,
    ENCOUNTERCLASS VARCHAR(50) NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_ENCOUNTER_COST DECIMAL(10, 2) NOT NULL,
    TOTAL_CLAIM_COST DECIMAL(10, 2) NOT NULL,
    PAYER_COVERAGE DECIMAL(10, 2) NOT NULL,
    REASONCODE VARCHAR(20),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE IMAGING_STUDIES (
    Id UUID PRIMARY KEY,
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    SERIES_UID VARCHAR(255) NOT NULL,
    BODYSITE_CODE VARCHAR(12) NOT NULL,
    BODYSITE_DESCRIPTION VARCHAR(255) NOT NULL,
    MODALITY_CODE VARCHAR(5) NOT NULL,
    MODALITY_DESCRIPTION VARCHAR(255) NOT NULL,
    INSTANCE_UID VARCHAR(255) NOT NULL,
    SOP_CODE VARCHAR(255) NOT NULL,
    SOP_DESCRIPTION VARCHAR(255) NOT NULL,
    PROCEDURE_CODE VARCHAR(20) NOT NULL
);

CREATE TABLE IMMUNIZATIONS (
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(5) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_COST DECIMAL(10, 2) NOT NULL
);

CREATE TABLE MEDICATIONS (
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    PAYER UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    BASE_COST DECIMAL(10, 2) NOT NULL,
    PAYER_COVERAGE DECIMAL(10, 2),
    DISPENSES INT NOT NULL,
    TOTALCOST DECIMAL(10, 2) NOT NULL,
    REASONCODE VARCHAR(255),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE OBSERVATIONS (
    DATE TIMESTAMP NOT NULL,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID,
    CATEGORY VARCHAR(255),
    CODE VARCHAR(50),
    DESCRIPTION VARCHAR(255),
    VALUE VARCHAR(255),
    UNITS VARCHAR(50),
    TYPE VARCHAR(50)
);

CREATE TABLE ORGANIZATIONS (
    Id UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP VARCHAR(15) NOT NULL,
    LAT DECIMAL(11, 8) NOT NULL,
    LON DECIMAL(11, 8) NOT NULL,
    PHONE VARCHAR(50),
    REVENUE DECIMAL(10, 2) NOT NULL,
    UTILIZATION INT NOT NULL
);

CREATE TABLE ALLERGIES (
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    SYSTEM VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    REACTION1 VARCHAR(50),
    DESCRIPTION1 VARCHAR(255),
    SEVERITY1 VARCHAR(50),
    REACTION2 VARCHAR(50),
    DESCRIPTION2 VARCHAR(255),
    SEVERITY2 VARCHAR(50),
    PRIMARY KEY (PATIENT, ENCOUNTER, CODE)
);

CREATE TABLE CAREPLANS (
    Id UUID PRIMARY KEY,
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    REASONCODE VARCHAR(50),
    REASONDESCRIPTION VARCHAR(255)
);

CREATE TABLE CLAIMS_TRANSACTIONS (
    ID UUID PRIMARY KEY,
    CLAIMID UUID NOT NULL,
    CHARGEID INT NOT NULL,
    PATIENTID UUID NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    AMOUNT DECIMAL(10, 2),
    METHOD VARCHAR(50),
    FROMDATE TIMESTAMP NOT NULL,
    TODATE TIMESTAMP NOT NULL,
    PLACEOFSERVICE UUID NOT NULL,
    PROCEDURECODE VARCHAR(50),
    MODIFIER1 VARCHAR(50),
    MODIFIER2 VARCHAR(50),
    DIAGNOSISREF1 INT,
    DIAGNOSISREF2 INT,
    DIAGNOSISREF3 INT,
    DIAGNOSISREF4 INT,
    UNITS INT,
    DEPARTMENTID INT,
    NOTES VARCHAR(255),
    UNITAMOUNT DECIMAL(10, 2),
    TRANSFEROUTID INT,
    TRANSFERTYPE VARCHAR(50),
    PAYMENTS DECIMAL(10, 2),
    ADJUSTMENTS DECIMAL(10, 2),
    TRANSFERS DECIMAL(10, 2),
    OUTSTANDING DECIMAL(10, 2),
    APPOINTMENTID UUID,
    LINENOTE VARCHAR(255),
    PATIENTINSURANCEID UUID,
    FEESCHEDULEID INT,
    PROVIDERID UUID,
    SUPERVISINGPROVIDERID UUID
);

CREATE TABLE CLAIMS (
    Id UUID PRIMARY KEY,
    PATIENTID UUID NOT NULL,
    PROVIDERID UUID NOT NULL,
    PRIMARYPATIENTINSURANCEID UUID,
    SECONDARYPATIENTINSURANCEID UUID,
    DEPARTMENTID INT NOT NULL,
    PATIENTDEPARTMENTID INT NOT NULL,
    DIAGNOSIS1 VARCHAR(50),
    DIAGNOSIS2 VARCHAR(50),
    DIAGNOSIS3 VARCHAR(50),
    DIAGNOSIS4 VARCHAR(50),
    DIAGNOSIS5 VARCHAR(50),
    DIAGNOSIS6 VARCHAR(50),
    DIAGNOSIS7 VARCHAR(50),
    DIAGNOSIS8 VARCHAR(50),
    REFERRINGPROVIDERID VARCHAR(50),
    APPOINTMENTID UUID NOT NULL,
    CURRENTILLNESSDATE TIMESTAMP,
    SERVICEDATE TIMESTAMP,
    SUPERVISINGPROVIDERID UUID,
    STATUS1 VARCHAR(50),
    STATUS2 VARCHAR(50),
    STATUSP VARCHAR(50),
    OUTSTANDING1 DECIMAL(10, 2),
    OUTSTANDING2 DECIMAL(10, 2),
    OUTSTANDINGP DECIMAL(10, 2),
    LASTBILLEDDATE1 TIMESTAMP,
    LASTBILLEDDATE2 TIMESTAMP,
    LASTBILLEDDATEP TIMESTAMP,
    HEALTHCARECLAIMTYPEID1 INT,
    HEALTHCARECLAIMTYPEID2 INT
);

CREATE TABLE CONDITIONS (
    START DATE NOT NULL,
    STOP DATE,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL
);

CREATE TABLE DEVICES (
    START TIMESTAMP NOT NULL,
    STOP TIMESTAMP,
    PATIENT UUID NOT NULL,
    ENCOUNTER UUID NOT NULL,
    CODE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    UDI VARCHAR(255) NOT NULL
);

--FOREIGN KEYS----------------------------------------------------------------------------------------------------------
ALTER TABLE PAYER_TRANSITIONS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE PAYER_TRANSITIONS
    ADD CONSTRAINT fk_payer FOREIGN KEY (PAYER) REFERENCES PAYERS(Id) ON DELETE CASCADE;
ALTER TABLE PAYER_TRANSITIONS
    ADD CONSTRAINT fk_secondary_payer FOREIGN KEY (SECONDARY_PAYER) REFERENCES PAYERS(Id) ON DELETE CASCADE;

ALTER TABLE PROCEDURES
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE PROCEDURES
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE PROVIDERS
    ADD CONSTRAINT fk_organization FOREIGN KEY (ORGANIZATION) REFERENCES ORGANIZATIONS(Id) ON DELETE CASCADE;

ALTER TABLE SUPPLIES
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE SUPPLIES
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE ENCOUNTERS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE ENCOUNTERS
    ADD CONSTRAINT fk_organization FOREIGN KEY (ORGANIZATION) REFERENCES ORGANIZATIONS(Id) ON DELETE CASCADE;
ALTER TABLE ENCOUNTERS
    ADD CONSTRAINT fk_provider FOREIGN KEY (PROVIDER) REFERENCES PROVIDERS(Id) ON DELETE CASCADE;
ALTER TABLE ENCOUNTERS
    ADD CONSTRAINT fk_payer FOREIGN KEY (PAYER) REFERENCES PAYERS(Id) ON DELETE CASCADE;


ALTER TABLE IMAGING_STUDIES
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE IMAGING_STUDIES
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE IMMUNIZATIONS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE IMMUNIZATIONS
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE MEDICATIONS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE MEDICATIONS
    ADD CONSTRAINT fk_payer FOREIGN KEY (PAYER) REFERENCES PAYERS(Id) ON DELETE CASCADE;
ALTER TABLE MEDICATIONS
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE OBSERVATIONS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE OBSERVATIONS
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE ALLERGIES
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE ALLERGIES
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE CAREPLANS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE CAREPLANS
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE CLAIMS_TRANSACTIONS
    ADD CONSTRAINT fk_claim FOREIGN KEY (CLAIMID) REFERENCES CLAIMS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS_TRANSACTIONS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS_TRANSACTIONS
    ADD CONSTRAINT fk_place_of_service FOREIGN KEY (PLACEOFSERVICE) REFERENCES ORGANIZATIONS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS_TRANSACTIONS
    ADD CONSTRAINT fk_appointment FOREIGN KEY (APPOINTMENTID) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS_TRANSACTIONS
    ADD CONSTRAINT fk_provider FOREIGN KEY (PROVIDERID) REFERENCES PROVIDERS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS_TRANSACTIONS
    ADD CONSTRAINT fk_supervising_provider FOREIGN KEY (SUPERVISINGPROVIDERID) REFERENCES PROVIDERS(Id) ON DELETE CASCADE;

ALTER TABLE CLAIMS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENTID) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS
    ADD CONSTRAINT fk_provider FOREIGN KEY (PROVIDERID) REFERENCES PROVIDERS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS
    ADD CONSTRAINT fk_primary_insurance FOREIGN KEY (PRIMARYPATIENTINSURANCEID) REFERENCES PAYERS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS
    ADD CONSTRAINT fk_secondary_insurance FOREIGN KEY (SECONDARYPATIENTINSURANCEID) REFERENCES PAYERS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS
    ADD CONSTRAINT fk_appointment FOREIGN KEY (APPOINTMENTID) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;
ALTER TABLE CLAIMS
    ADD CONSTRAINT fk_supervising_provider FOREIGN KEY (SUPERVISINGPROVIDERID) REFERENCES PROVIDERS(Id) ON DELETE CASCADE;

ALTER TABLE CONDITIONS
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE CONDITIONS
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

ALTER TABLE DEVICES
    ADD CONSTRAINT fk_patient FOREIGN KEY (PATIENT) REFERENCES PATIENTS(Id) ON DELETE CASCADE;
ALTER TABLE DEVICES
    ADD CONSTRAINT fk_encounter FOREIGN KEY (ENCOUNTER) REFERENCES ENCOUNTERS(Id) ON DELETE CASCADE;

--INDEXES---------------------------------------------------------------------------------------------------------------
CREATE INDEX idx_payer_transitions_patient ON PAYER_TRANSITIONS(PATIENT);
CREATE INDEX idx_payer_transitions_payer ON PAYER_TRANSITIONS(PAYER);

CREATE INDEX idx_encounters_patient ON ENCOUNTERS(PATIENT);
CREATE INDEX idx_encounters_payer ON ENCOUNTERS(PAYER);

CREATE INDEX idx_procedures_encounter ON PROCEDURES(ENCOUNTER);
CREATE INDEX idx_medications_payer ON MEDICATIONS(PAYER);

--VIEWS-----------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE VIEW medication_summary AS
SELECT description, SUM(dispenses) AS total_dispenses
FROM medications
GROUP BY description;

CREATE OR REPLACE VIEW supply_summary AS
SELECT description, SUM(quantity) AS total_quantity
FROM supplies
GROUP BY description
ORDER BY total_quantity DESC;